import { Check, Circle, Copy, ExternalLink, Send } from "lucide-react";
import { PageHeader, Panel, StatusBadge } from "@/components/ui";

const steps = [
  { title: "Install the SDK", done: true, code: "pnpm add @global-security/nextjs" },
  { title: "Add environment variables", done: true, code: "GLOBAL_SECURITY_SITE_ID=site_aurora_7d31\nGLOBAL_SECURITY_SECRET_KEY=sk_live_••••\nGLOBAL_SECURITY_ENDPOINT=https://security.example.com" },
  { title: "Initialize the client", done: false, code: "import { createSecurityClient } from '@global-security/nextjs';\n\nexport const security = createSecurityClient({\n  siteId: process.env.GLOBAL_SECURITY_SITE_ID!,\n  secretKey: process.env.GLOBAL_SECURITY_SECRET_KEY!,\n  endpoint: process.env.GLOBAL_SECURITY_ENDPOINT!,\n});" },
];

export default function IntegrationPage() { return <div className="page"><PageHeader eyebrow="Developer" title="Integration" description="Connect Aurora Commerce to begin streaming authentication and security telemetry." actions={[{ label: "Open documentation", icon: ExternalLink }]} /><div className="detail-grid"><Panel title="Next.js setup" subtitle="Three steps to your first verified event"><div>{steps.map((step, index) => <div className="form-section" key={step.title}><div style={{ display: "flex", alignItems: "center", gap: 9, marginBottom: 12 }}>{step.done ? <Check size={16} color="var(--success)" /> : <Circle size={16} color="var(--ink-tertiary)" />}<h3 className="form-heading" style={{ margin: 0 }}>{index + 1}. {step.title}</h3></div><pre className="code-block"><code>{step.code}</code><button className="icon-button" style={{ position: "absolute", top: 8, right: 8, color: "#d8e4e5" }} aria-label={`Copy ${step.title}`}><Copy size={13} /></button></pre></div>)}</div></Panel><div style={{ display: "grid", gap: 16, alignContent: "start" }}><Panel title="Connection"><div className="panel-body"><StatusBadge>Connected</StatusBadge><dl style={{ margin: "16px 0 0", display: "grid", gap: 12 }}><div><dt className="strip-label">Last event</dt><dd style={{ margin: "4px 0 0" }}>8 seconds ago</dd></div><div><dt className="strip-label">SDK version</dt><dd className="mono" style={{ margin: "4px 0 0" }}>v0.8.4</dd></div><div><dt className="strip-label">Environment</dt><dd style={{ margin: "4px 0 0" }}>Production</dd></div></dl></div></Panel><Panel title="Verify installation"><div className="panel-body"><p className="form-help">Send a safe synthetic event to confirm credentials and connectivity.</p><button className="button primary" style={{ width: "100%" }}><Send size={14} />Send test event</button></div></Panel></div></div></div>; }
